CREATE IF NOT EXISTS TABLE CHAT(
    CHAT_ID INT PRIMARY KEY NOT NULL,
    TYPE VARCHAR(256),
);

CREATE IF NOT EXISTS TABLE REPO{
       ID SERIAL PRIMARY KEY NOT NULL,
       NAME VARCHAR(256) NOT NULL,
       OWNER VARCHAR(256) NOT NULL,
       LINK VARCHAR(512) NOT NULL,
       LAST_COMMIT TIMESTAMP,
       LAST_ISSUE TIMESTAMP,
       LAST_PULL_REQUEST TIMESTAMP,
};

CREATE IF NOT EXISTS TABLE CHAT_REPO_RECORD{
    ID SERIAL PRIMARY KEY NOT NULL,
    СHAT INTEGER REFERENCES CHAT(CHAT_ID),
    REPO INTEGER REFERENCES REPO(ID),
    TAGS VARCHAR(256)[],
    EVENTS VARCHAR(256)[],
};

CREATE IF NOT EXISTS INDEX CHAT_ID_INDEX ON CHAT USING HASH(CHAT_ID);

CREATE IF NOT EXISTS INDEX REPO_ID_INDEX ON REPO USING HASH(ID);

CREATE IF NOT EXISTS INDEX REPO_OWNER_NAME_INDEX ON REPO(NAME, OWNER);

CREATE IF NOT EXISTS INDEX CHAT_ID_REPO_INDEX ON CHAT_REPO_RECORD USING HASH(CHAT);

CREATE IF NOT EXISTS INDEX CHAT_ID_REPO_INDEX ON CHAT_REPO_RECORD USING HASH(ID);